sudo: required

# CMake 2.8.9 is needed to build libswiftnav, but Travis only supports
# an earlier version. This sets up that dependency. See also:
#   https://gist.github.com/winterz/10cc2741d466cbd8ff21
#   https://github.com/travis-ci/travis-ci/issues/2030

before_install:
  - sudo add-apt-repository --yes ppa:kalakris/cmake
  - travis_retry sudo apt-get update -qq
  - sudo apt-get install cmake check
  - export LD_LIBRARY_PATH=/usr/local/lib

script:
  # Test libswiftnav
  - mkdir build
  - cd build/
  - cmake ../
  - make
  - sudo make install
  # Test libswiftnav-python
  - cd ../python
  - sudo pip install tox
  - tox
